version = 1

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Licensing statement required for GHA tests and linting to pass for only this repository

[[annotations]]
path = [
    "samples/**",
    "test-packages-fixed.Dockerfile",
    "baseline-network.json",
    "pki/**/*.pem",
    "pki/**/*.crt",
    "pki/**/*.key",
    "pki/**/*.csr",
    "pki/**/*.srl",
    "pki/*.pem",
    "pki/*.crt",
    "pki/*.key",
    "pki/*.csr",
    "pki/*.srl",
    "pki/*.conf.template",
    "pki/*.asc"
]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2025 The Linux Foundation"
